<?php

use Illuminate\Database\Seeder;
use App\M_Kota;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $table = new M_Kota();
        $items = [
            [1, "SIMEULUE"],
            [1, "ACEH SINGKIL"],
            [1, "ACEH SELATAN"],
            [1, "ACEH TENGGARA"],
            [1, "ACEH TIMUR"],
            [1, "ACEH TENGAH"],
            [1, "ACEH BARAT"],
            [1, "ACEH BESAR"],
            [1, "PIDIE"],
            [1, "BIREUEN"],
            [1, "ACEH UTARA"],
            [1, "ACEH BARAT DAYA"],
            [1, "GAYO LUES"],
            [1, "ACEH TAMIANG"],
            [1, "NAGAN RAYA"],
            [1, "ACEH JAYA"],
            [1, "BENER MERIAH"],
            [1, "BANDA ACEH"],
            [1, "SABANG"],
            [1, "LANGSA"],
            [1, "LHOKSEUMAWE"],
            [2, "NIAS"],
            [2, "MANDAILING NATAL"],
            [2, "TAPANULI SELATAN"],
            [2, "TAPANULI TENGAH"],
            [2, "TAPANULI UTARA"],
            [2, "TOBA SAMOSIR"],
            [2, "LABUHAN BATU"],
            [2, "ASAHAN"],
            [2, "SIMALUNGUN"],
            [2, "DAIRI"],
            [2, "KARO"],
            [2, "DELI SERDANG"],
            [2, "LANGKAT"],
            [2, "NIAS SELATAN"],
            [2, "HUMBANG HASUNDUTAN"],
            [2, "PAKPAK BHARAT"],
            [2, "SAMOSIR"],
            [2, "SERDANG BEDAGAI"],
            [2, "SIBOLGA"],
            [2, "TANJUNG BALAI"],
            [2, "PEMATANG SIANTAR"],
            [2, "TEBING TINGGI"],
            [2, "MEDAN"],
            [2, "BINJAI"],
            [2, "PADANGSIDIMPUAN"],
            [3, "KEPULAUAN MENTAWAI"],
            [3, "PESISIR SELATAN"],
            [3, "SOLOK"],
            [3, "SAWAHLUNTO/SIJUNJUNG"],
            [3, "TANAH DATAR"],
            [3, "PADANG PARIAMAN"],
            [3, "AGAM"],
            [3, "LIMA PULUH KOTO"],
            [3, "PASAMAN"],
            [3, "SOLOK SELATAN"],
            [3, "DHARMASRAYA"],
            [3, "PASAMAN BARAT"],
            [3, "PADANG"],
            [3, "KABUPATEN SOLOK"],
            [3, "SAWAH LUNTO"],
            [3, "PADANG PANJANG"],
            [3, "BUKITTINGGI"],
            [3, "PAYAKUMBUH"],
            [3, "PARIAMAN"],
            [4, "KUANTAN SINGINGI"],
            [4, "INDRAGIRI HULU"],
            [4, "INDRAGIRI HILIR"],
            [4, "PELALAWAN"],
            [4, "S I A K"],
            [4, "KAMPAR"],
            [4, "ROKAN HULU"],
            [4, "BENGKALIS"],
            [4, "ROKAN HILIR"],
            [4, "PEKAN BARU"],
            [4, "D U M A I"],
            [5, "KERINCI"],
            [5, "MERANGIN"],
            [5, "SAROLANGUN"],
            [5, "BATANG HARI"],
            [5, "MUARO JAMBI"],
            [5, "TANJUNG JABUNG TIMUR"],
            [5, "TANJUNG JABUNG BARAT"],
            [5, "TEBO"],
            [5, "BUNGO"],
            [5, "JAMBI"],
            [6, "OGAN KOMERING ULU"],
            [6, "OGAN KOMERING ILIR"],
            [6, "MUARA ENIM"],
            [6, "LAHAT"],
            [6, "MUSI RAWAS"],
            [6, "MUSI BANYU ASIN"],
            [6, "BANYUASIN"],
            [6, "OKU SELATAN"],
            [6, "OKU TIMUR"],
            [6, "OGAN ILIR"],
            [6, "PALEMBANG"],
            [6, "PRABUMULIH"],
            [6, "PAGAR ALAM"],
            [6, "LUBUK LINGGAU"],
            [7, "BENGKULU SELATAN"],
            [7, "REJANG LEBONG"],
            [7, "BENGKULU UTARA"],
            [7, "KAUR"],
            [7, "SELUMA"],
            [7, "MUKOMUKO"],
            [7, "LEBONG"],
            [7, "KEPAHIANG"],
            [7, "BENGKULU"],
            [8, "LAMPUNG BARAT"],
            [8, "TANGGAMUS"],
            [8, "LAMPUNG SELATAN"],
            [8, "LAMPUNG TIMUR"],
            [8, "LAMPUNG TENGAH"],
            [8, "LAMPUNG UTARA"],
            [8, "WAY KANAN"],
            [8, "TULANGBAWANG"],
            [8, "BANDAR LAMPUNG"],
            [8, "METRO"],
            [9, "BANGKA"],
            [9, "BELITUNG"],
            [9, "BANGKA BARAT"],
            [9, "BANGKA TENGAH"],
            [9, "BANGKA SELATAN"],
            [9, "BELITUNG TIMUR"],
            [9, "PANGKAL PINANG"],
            [10, "KARIMUN"],
            [10, "KEPULAUAN RIAU"],
            [10, "NATUNA"],
            [10, "LINGGA"],
            [10, "B A T A M"],
            [10, "TANJUNG PINANG"],
            [11, "KEPULAUAN SERIBU"],
            [11, "JAKARTA SELATAN"],
            [11, "JAKARTA TIMUR"],
            [11, "JAKARTA PUSAT"],
            [11, "JAKARTA BARAT"],
            [11, "JAKARTA UTARA"],
            [12, "KABUPATEN BOGOR"],
            [12, "KABUPATEN SUKABUMI"],
            [12, "CIANJUR"],
            [12, "KABUPATEN BANDUNG"],
            [12, "GARUT"],
            [12, "TASIKMALAYA"],
            [12, "CIAMIS"],
            [12, "KUNINGAN"],
            [12, "KABUPATEN CIREBON"],
            [12, "MAJALENGKA"],
            [12, "SUMEDANG"],
            [12, "INDRAMAYU"],
            [12, "SUBANG"],
            [12, "PURWAKARTA"],
            [12, "KARAWANG"],
            [12, "KABUPATEN BEKASI"],
            [12, "KOTA BOGOR"],
            [12, "KOTA SUKABUMI"],
            [12, "KOTA BANDUNG"],
            [12, "KOTA CIREBON"],
            [12, "KOTA BEKASI"],
            [12, "DEPOK"],
            [12, "KOTA CIMAHI"],
            [12, "KOTA TASIKMALAYA"],
            [12, "BANJAR"],
            [13, "CILACAP"],
            [13, "BANYUMAS"],
            [13, "PURBALINGGA"],
            [13, "BANJARNEGARA"],
            [13, "KEBUMEN"],
            [13, "PURWOREJO"],
            [13, "WONOSOBO"],
            [13, "MAGELANG"],
            [13, "BOYOLALI"],
            [13, "KLATEN"],
            [13, "SUKOHARJO"],
            [13, "WONOGIRI"],
            [13, "KARANGANYAR"],
            [13, "SRAGEN"],
            [13, "GROBOGAN"],
            [13, "BLORA"],
            [13, "REMBANG"],
            [13, "PATI"],
            [13, "KUDUS"],
            [13, "JEPARA"],
            [13, "DEMAK"],
            [13, "SEMARANG"],
            [13, "TEMANGGUNG"],
            [13, "KENDAL"],
            [13, "BATANG"],
            [13, "PEKALONGAN"],
            [13, "PEMALANG"],
            [13, "TEGAL"],
            [13, "BREBES"],
            [13, "KABUPATEN MAGELANG"],
            [13, "SURAKARTA"],
            [13, "SALATIGA"],
            [13, "KABUPATEN SEMARANG"],
            [13, "PEKALONGAN"],
            [13, "TEGAL"],
            [14, "KULON PROGO"],
            [14, "BANTUL"],
            [14, "GUNUNG KIDUL"],
            [14, "SLEMAN"],
            [14, "YOGYAKARTA"],
            [15, "PACITAN"],
            [15, "PONOROGO"],
            [15, "TRENGGALEK"],
            [15, "TULUNGAGUNG"],
            [15, "BLITAR"],
            [15, "KEDIRI"],
            [15, "MALANG KAB"],
            [15, "LUMAJANG"],
            [15, "JEMBER"],
            [15, "BANYUWANGI"],
            [15, "BONDOWOSO"],
            [15, "SITUBONDO"],
            [15, "PROBOLINGGO KABUPATEN"],
            [15, "PASURUAN"],
            [15, "SIDOARJO"],
            [15, "MOJOKERTO"],
            [15, "JOMBANG"],
            [15, "NGANJUK"],
            [15, "MADIUN"],
            [15, "MAGETAN"],
            [15, "NGAWI"],
            [15, "BOJONEGORO"],
            [15, "TUBAN"],
            [15, "LAMONGAN"],
            [15, "GRESIK"],
            [15, "BANGKALAN"],
            [15, "SAMPANG"],
            [15, "PAMEKASAN"],
            [15, "SUMENEP"],
            [15, "KEDIRI"],
            [15, "BLITAR KABUPATEN"],
            [15, "MALANG KOTA"],
            [15, "PROBOLINGGO"],
            [15, "KABUPATEN PASURUAN"],
            [15, "KOTA MOJOKERTO"],
            [15, "KABUPATEN MADIUN"],
            [15, "SURABAYA"],
            [15, "BATU"],
            [16, "PANDEGLANG"],
            [16, "LEBAK"],
            [16, "KABUPATEN TANGERANG"],
            [16, "KOTA SERANG"],
            [16, "KOTA TANGERANG"],
            [16, "CILEGON"],
            [17, "JEMBRANA"],
            [17, "TABANAN"],
            [17, "BADUNG"],
            [17, "GIANYAR"],
            [17, "KLUNGKUNG"],
            [17, "BANGLI"],
            [17, "KARANG ASEM"],
            [17, "BULELENG"],
            [17, "DENPASAR"],
            [18, "LOMBOK BARAT"],
            [18, "LOMBOK TENGAH"],
            [18, "LOMBOK TIMUR"],
            [18, "SUMBAWA"],
            [18, "DOMPU"],
            [18, "BIMA"],
            [18, "SUMBAWA BARAT"],
            [18, "MATARAM"],
            [18, "KABUPATEN BIMA"],
            [19, "SUMBA BARAT"],
            [19, "SUMBA TIMUR"],
            [19, "KUPANG"],
            [19, "TIMOR TENGAH SELATAN"],
            [19, "TIMOR TENGAH UTARA"],
            [19, "BELU"],
            [19, "ALOR"],
            [19, "LEMBATA"],
            [19, "FLORES TIMUR"],
            [19, "SIKKA"],
            [19, "ENDE"],
            [19, "NGADA"],
            [19, "MANGGARAI"],
            [19, "ROTE NDAO"],
            [19, "MANGGARAI BARAT"],
            [19, "KABUPATEN KUPANG"],
            [20, "SAMBAS"],
            [20, "BENGKAYANG"],
            [20, "LANDAK"],
            [20, "MEMPAWAH"],
            [20, "SANGGAU"],
            [20, "KETAPANG"],
            [20, "SINTANG"],
            [20, "KAPUAS HULU"],
            [20, "SEKADAU"],
            [20, "MELAWI"],
            [20, "PONTIANAK"],
            [20, "SINGKAWANG"],
            [21, "KOTAWARINGIN BARAT"],
            [21, "KOTAWARINGIN TIMUR"],
            [21, "KAPUAS"],
            [21, "BARITO SELATAN"],
            [21, "BARITO UTARA"],
            [21, "SUKAMARA"],
            [21, "LAMANDAU"],
            [21, "SERUYAN"],
            [21, "KATINGAN"],
            [21, "PULANG PISAU"],
            [21, "GUNUNG MAS"],
            [21, "BARITO TIMUR"],
            [21, "MURUNG RAYA"],
            [21, "PALANGKA RAYA"],
            [22, "TANAH LAUT"],
            [22, "KOTA BARU"],
            [22, "BANJAR"],
            [22, "BARITO KUALA"],
            [22, "TAPIN"],
            [22, "HULU SUNGAI SELATAN"],
            [22, "HULU SUNGAI TENGAH"],
            [22, "HULU SUNGAI UTARA"],
            [22, "TABALONG"],
            [22, "TANAH BUMBU"],
            [22, "BALANGAN"],
            [22, "BANJARMASIN"],
            [22, "BANJAR BARU"],
            [23, "PASIR"],
            [23, "KUTAI BARAT"],
            [23, "KUTAI"],
            [23, "KUTAI TIMUR"],
            [23, "BERAU"],
            [23, "MALINAU"],
            [23, "BULONGAN"],
            [23, "NUNUKAN"],
            [23, "PENAJAM PASER UTARA"],
            [23, "BALIKPAPAN"],
            [23, "SAMARINDA"],
            [23, "TARAKAN"],
            [23, "BONTANG"],
            [24, "BOLAANG MONGONDOW"],
            [24, "MINAHASA"],
            [24, "SANGIHE TALAUD"],
            [24, "KEPULAUAN TALAUD"],
            [24, "MINAHASA SELATAN"],
            [24, "MINAHASA UTARA"],
            [24, "MANADO"],
            [24, "BITUNG"],
            [24, "TOMOHON"],
            [25, "BANGGAI KEPULAUAN"],
            [25, "BANGGAI"],
            [25, "MOROWALI"],
            [25, "POSO"],
            [25, "DONGGALA"],
            [25, "TOLI-TOLI"],
            [25, "BUOL"],
            [25, "PARIGI MOUTONG"],
            [25, "TOJO UNA-UNA"],
            [25, "PALU"],
            [26, "SELAYAR"],
            [26, "BULUKUMBA"],
            [26, "BANTAENG"],
            [26, "JENEPONTO"],
            [26, "TAKALAR"],
            [26, "GOWA"],
            [26, "SINJAI"],
            [26, "MAROS"],
            [26, "PANGKAJENE KEPULAUAN"],
            [26, "BARRU"],
            [26, "BONE"],
            [26, "SOPPENG"],
            [26, "WAJO"],
            [26, "SIDENRENG RAPPANG"],
            [26, "PINRANG"],
            [26, "ENREKANG"],
            [26, "LUWU"],
            [26, "TANA TORAJA"],
            [33, "KABUPATEN POLEWALI MANDAR"],
            [26, "[EX]MAJENE"],
            [26, "[EX]MAMUJU"],
            [26, "LUWU UTARA"],
            [26, "[EX]MAMASA"],
            [33, "[EX]MAMUJU UTARA"],
            [26, "LUWU TIMUR"],
            [26, "UJUNG PANDANG"],
            [26, "PARE-PARE"],
            [26, "PALOPO"],
            [27, "BUTON"],
            [27, "MUNA"],
            [27, "KENDARI"],
            [27, "KOLAKA"],
            [27, "KONAWE SELATAN"],
            [27, "BOMBANA"],
            [27, "WAKATOBI"],
            [27, "KOLAKA UTARA"],
            [27, "KABUPATEN KENDARI"],
            [27, "BAU-BAU"],
            [28, "KAB. BOALEMO"],
            [28, "KAB. GORONTALO"],
            [28, "KAB. POHUWATO"],
            [28, "KAB. BONE BOLANGO"],
            [28, "KOTA GORONTALO"],
            [29, "MALUKU TENGGARA BARAT"],
            [29, "MALUKU TENGGARA"],
            [29, "MALUKU TENGAH"],
            [29, "BURU"],
            [29, "KEPULAUAN ARU"],
            [29, "SERAM BAGIAN BARAT"],
            [29, "SERAM BAGIAN TIMUR"],
            [29, "AMBON"],
            [30, "HALMAHERA BARAT"],
            [30, "HALMAHERA TENGAH"],
            [30, "KEPULAUAN SULA"],
            [30, "HALMAHERA SELATAN"],
            [30, "HALMAHERA UTARA"],
            [30, "HALMAHERA TIMUR"],
            [30, "TERNATE"],
            [30, "TIDORE KEPULAUAN"],
            [31, "FAK-FAK"],
            [31, "KAIMANA"],
            [31, "TELUK WONDAMA"],
            [31, "TELUK BINTUNI"],
            [31, "MANOKWARI"],
            [31, "SORONG SELATAN"],
            [31, "SORONG"],
            [31, "RAJA AMPAT"],
            [31, "KABUPATEN SORONG"],
            [32, "MERAUKE"],
            [32, "JAYAWIJAYA"],
            [32, "JAYAPURA"],
            [32, "NABIRE"],
            [32, "YAPEN WAROPEN"],
            [32, "BIAK NUMFOR"],
            [32, "PANIAI"],
            [32, "PUNCAK JAYA"],
            [32, "MIMIKA"],
            [32, "BOVEN DIGOEL"],
            [32, "MAPPI"],
            [32, "ASMAT"],
            [32, "YAHUKIMO"],
            [32, "PEGUNUNGAN BINTANG"],
            [32, "TOLIKARA"],
            [32, "SARMI"],
            [32, "KEEROM"],
            [32, "WAROPEN"],
            [32, "SUPIORI"],
            [32, "KOTA JAYAPURA"],
            [33, "POLEWALI MANDAR"],
            [33, "MAJENE"],
            [33, "MAMUJU"],
            [33, "KABUPATEN MAMASA"],
            [33, "KABUPATEN MAMUJU UTARA"],
            [8, "MESUJI"],
            [8, "PESAWARAN"],
            [8, "PRINGSEWU"],
            [8, "TULANG BAWANG BARAT"],
            [26, "TORAJA UTARA"],
            [32, "PAPUA"],
            [2, "GUNUNG SITOLI"],
            [2, "LABUHANBATU UTARA"],
            [2, "LABUHANBATU SELATAN"],
            [2, "BATUBARA"],
            [2, "NIAS UTARA"],
            [2, "NIAS BARAT"],
            [2, "PADANG LAWAS UTARA"],
            [2, "PADANG LAWAS"],
            [4, "KEPULAUAN MERANTI"],
            [34, "KOTA TARAKAN"],
            [34, "BULUNGAN"],
            [34, "KABUPATEN NUNUKAN"],
            [34, "MALINAU"],
            [34, "TANA TIDUNG"],
            [6, "EMPAT LAWANG"],
            [5, "SUNGAI PENUH"],
            [24, "BOLAANG MONGONDOW SELATAN"],
            [24, "BOLAANG MONGONDOW TIMUR"],
            [24, "BOLAANG MONGONDOW UTARA"],
            [24, "KEP. SIAU TAGULANDANG BIARO"],
            [24, "MINAHASA TENGGARA"],
            [24, "KOTAMOBAGU"],
            [33, "MAMUJU TENGAH"],
            [25, "BANGGAI LAUT"],
            [25, "SIGI"],
            [25, "MOROWALI UTARA"],
            [6, "PENUKAL ABAB LEMATANG ILIR"],
            [6, "PMUSI RAWAS UTARA"],
            [20, "KUBU RAYA"],
            [20, "KAYONG UTARA"],
            [18, "LOMBOK UTARA"],
            [1, "SUBULUSSALAM"],
            [1, "PIDIE JAYA"],
            [30, "PULAI MOROTAI"],
            [30, "PULAU TALIABU"],
            [10, "ANAMBAS"],
            [16, "KAB SERANG"],
            [16, "TANGERANG SELATAN"],
            [19, "SABU RAIJUA"],
            [8, "PESISIR BARAT"],
            [12, "KABUPATEN BANDUNG BARAT"],
            [12, "KABUPATEN PANGANDARAN"],
            [28, "KAB. GORONTALO UTARA"]
        ];
        
        // Insert Daftar Kota Kabupaten
        foreach ($items as $item) {
            $table->insert([
                "id_provinsi"   => $item[0],
                "nama_kota" => $item[1]
            ]);
        }
    }
}
